### PR TITLE
more absolute path replacement

### PR DESCRIPTION
**Pull request by trob**

### CODE REVIEW

**Comment by trob** [comment]
$base is needed for xml and "dump" string replace
JURI::base(false); = scheme, host, port, subdir (with trailing /) (uri->getHost() was without trailing /)

**Comment by trob** [comment]
Use JURI::root() because JURI::base will be xxx/administrator/ if used from the backend.

JURI::root() should be identical to COM_FABRIK_LIVESITE ??

**Comment by trob** [comment]
In the xml part
if (!strstr($img['src'], $base))
won't be correct in case of an existing absolute path to somewhere else (it would prepend the base in this case).
So I think it must be
if (!strstr($img['src'], '://')) to test if any scheme it set
?

**Comment by cheesegrits** [comment]
Yes, I mentioned that in the thread we have going about that.  Although tbh, I doubt the XML part gets run that often, as there are many things in an HTML structure which will break simpleXMLElement, that I didn't know about when I wrote that code.  So I suspect that more often than not that throws an exception and the catch code gets run, doing the dumb replace.

**Comment by cheesegrits** [comment]
But yes, go ahead and do that before I merge.

**Comment by cheesegrits** [comment]
I think I fixed this in another commit?

**Pull request closed without merging**
