### PR TITLE
[CHANGE] time element title to language string

### PR DESCRIPTION
**Pull request by skurvish**
So that it can be overridden using a language override. I need to be able to change this to advise my members that the time is 24 hours, they can't seem to see it right in front of them.

### CODE REVIEW

**Comment by pollen8** [comment]
thanks - I've merged that for you

**Comment by trob** [comment]
no luck for those who have already use "time" for overriding...

**Comment by skurvish** [comment]
Not sure what you mean by that? Can you elaborate?

**Comment by trob** [comment]
It was possible to do a language override on "time", without override the time popup was showing "time" in all languages (e.g. I had overriden "time" with the German "Zeit").

Now the time picker popup is showing "PLG_ELEMENT_DATE_TIME_LABEL" as long as this language string is not explicitly added to the language files (no idea why Joomla is not fetching the English translation in this case).

**Pull request merged**
