### PR TITLE
Autocreated FK field name as parenttablename_pkname

### PR DESCRIPTION
**Pull request by jaanusnurmoja**
Not necessarily for immediate merge. Trying to make first steps implementing my ideas written in Fabrik github wiki
https://github.com/Fabrik/fabrik/wiki/Ideas-for-future-from-Jaanus#joins-autocreated-table-and-element-names

After group is saved as repeat group the autocreated FK name was always parent_id but being autocreated as `[your_parent_table_name]_[your_parent_table_pk]` (e.g cities_id or counties_CCODE, depending on the pk name) it would be more informative as the field name shows where the data comes from

### CODE REVIEW

**Comment by cheesegrits** [comment]
I don't think you've located all the places where we assume it's called parent_id, like in unMakeJoinedGroup?

**Comment by jaanusnurmoja** [comment]
Not found yet more places when talking about groups.
As much I can see unMakeJoinedGroup doesn't assume such fk name .

2015-03-18 0:50 GMT+02:00 Hugh Messenger <notifications@github.com>:

**Comment by jaanusnurmoja** [comment]
During tests I noticed that indeed, there was planned such feature - when the join is created via group admin (repeat button=yes) then setting repeat button back to "No" would unmake the join as well. But this is currently disabled as "this was destroying legitimate joins" (Rob's comment in /administrator/components/com_fabrik/models/group.php under function save($data))

So currently if we set repeat button back to "No" then the join is preserved (just becomes not repeated). IMO it's safer and it wouldn't make sense to have a dilemma "no repeat + no join or repeat + join".  And I should probably rethink the repeat button related ideas (no big sense to make this param=2 although it works as expected)

**Comment by jaanusnurmoja** [comment]
Closing this - made a new PR https://github.com/Fabrik/fabrik/pull/1743 for master.

**Pull request closed without merging**
