### PR TITLE
Fix list sort icons

### PR DESCRIPTION
**Pull request by Sophist-UK**
1. Make list sort icons consistent with Joomla standard usage.

2. Various tweaks to list.js including improved ajax calls.

Originally submitted as part of #1304.

### CODE REVIEW

**Comment by pollen8** [comment]
Hi Paul
can you make one PR per issue - browsing through this PR there are multiple changes. With JS functions completely removed, changed, alerts altered to console.logs etc. I'm sure most of its fine, but there's no explanation as to why those changes are there in the PR....

Its best practice to make a branch per feature/change you are working on. That way you can very easily make a PR specific to that single change.

If you need all your changes in a local site, create another branch which will pull in all your feature branches

**Comment by Sophist-UK** [comment]
This was originally submitted as part of an even bigger one - so this is already cut down. I accept that there are several changes, however, the only significant change of functionality is the icons - the rest of the js changes just improve reliability. But I can split them out again if you want.

**Comment by pollen8** [comment]
I think Hugh has resovled this one with this commit https://github.com/Fabrik/fabrik/commit/2feff0d7befd981c89fee1983da8e648f7a24377
If you would like to open a new ticket for the list js stuff I can merge that

**Comment by Sophist-UK** [comment]
Can't you just grab and merge the commit https://github.com/Sophist-UK/Sophist_fabrik/commit/3712bc1b5f2058f797d4aabe7c756a06938d35e4

**Pull request closed without merging**
