### PR TITLE
Data picker jquery time close

### PR DESCRIPTION
**Pull request by pollen8**
mootools hide() is being suppressed in certain cases. Really thought this one had been resolved. 
Might be related to this
http://fabrikar.com/forums/index.php?threads/problem-with-datetime-element-with-warp-framework.43654/
Seems sensible to use Jquery.hide instead

### CODE REVIEW

**Comment by cheesegrits** [comment]
LOL ... I ran across example the same thing last week ...

https://github.com/Fabrik/fabrik/commit/cf4e699c339c08a12cb7cb9487ab0d1804c2a820

**Comment by cheesegrits** [comment]
BTW, will those changes to package.json bite me?

**Comment by cheesegrits** [comment]
And ... do you want me to delete these branches when I merge them?

**Comment by pollen8** [comment]
i couldn't install the node modules without updating the package.json.
If you don;'t npm update then it won't affect you, although it shouldn't matter even after the update.
Yeah please delete branches. I'm just doing any commit I make this way as I'm not looking at the code on a day to day basis so would prefer you vet things before they go in.

**Pull request merged**
