### PR TITLE
Correct wrong display of icons in list view.

### PR DESCRIPTION
**Pull request by skurvish**

### CODE REVIEW

**Comment by Sophist-UK** [comment]
1. If there was a forum discussion about this issue, please add a link to it here.

2. Can you please provide before and after screen shots and before and after examples of the HTML?

3. Can you please explain why deleting this line fixes the problem? Or since we can assume that it fixes the problem for you, can you explain why it fixes the problem without creating any side effects for other users?

Thx.

**Comment by Sophist-UK** [comment]
The forum discussion is at http://fabrikar.com/forums/index.php?threads/icon-rendered-even-when-replace-with-icons-is-no.48789

**Comment by skurvish** [comment]
I attach a screenshot of the element settings: 
image

Without the change this is what the list looks like: 
image and the HTML: 
image


With the change this is what it looks like: 
image and the HTML: 
image

**Comment by skurvish** [comment]
Now, having said that, if the purpose of the Replace with Icons is strictly for replacements of named element database icons, and the static icon file is for fixed icons irrespective of whether named database element icons exist, then this change would be incorrect and we should rather change the descriptions to make this more clear.

**Comment by Sophist-UK** [comment]
I agree that the before HTML is wrong - as per the forum discussion. However...

What yours settings has asked for is to replace the value of the field with a heart30 icon - and the before screen shot has done that, whilst the after screen-shot hasn't replaced it and we still see the field value.

Therefore the code change in this PR is clearly incorrect. Back to the drawing board I'm afraid...

**Comment by skurvish** [comment]
I am OK with killing this commit. The before code is still very wrong and I will be submitting another PR to fix that. I am OK with the usage of Replace with icons to be replacement with icons equal to the database field names, and replace with static icon to be fixed. I think we can assume that the replace with static overrides the database? If so then that is how it works now. If not then the logic for icon selection will need to be changed.

**Comment by Sophist-UK** [comment]
When you do the replacement PR, we need to decide whether the logic should stay as it currently is:

* Even if you have set `Replace with (dynamic) icon` to Yes, if you have also said `Replace with static icon`, then this is used regardless of the `Replace with icon` setting; or

switch to another algorithm:

* If `Replace with icon` is Yes, then use a non-null value as icon and use the `Replace with static icon` value only if the `Replace with icon` field is empty. This choice will impact anyone who has set both dynamic and static values, but fixing it is easy enough.

I have thought about this quite a bit and am torn between breaking backwards compatibility for anyone who has set both dynamic and static icons. In the end I feel it is better to preserve backwards compatibility and leave the logic as it is now, because I think there may be many people who have set Replace with icon to Yes on a field even though they intend the static icon to be used.

**Comment by skurvish** [comment]
I concur.

**Pull request closed without merging**
