### PR TITLE
add PK to webservice row for update

### PR DESCRIPTION
**Pull request by trob**
I think it could be done somewhere in list.php (if PK not set-> set it) - but I won't touch it.

### CODE REVIEW

**Comment by cheesegrits** [comment]
What issue is this fixing?  Just so's I can test ...

**Comment by trob** [comment]
www.fabrikar.com/forums/index.php?threads/update-exsisting-record-in-list-error.40808/

**Comment by cheesegrits** [comment]
Oh, OK, I gotcha.

The better place to do this would probably be in map(), which is where the $data from the list model is being re-mapped for use with storeLocally(), and where the PK is being dropped (because it's not part of the "map").  Doesn't make a huge difference, and if you don't have time to redo it that way, don't worry about it.  It would be a bit harder to do in map(), anyway.

Only other comment is that you could set up $primaryKey outside of the foreach, as that's not going to change, not point redoing that on every time round the loop.  Again, if you don't have time, don't worry about.

Let me know ...

**Comment by trob** [comment]
moved $primarykey outside loop

**Pull request merged**
