### PR TITLE
Create fr-FR.plg_fabrik_element_timestamp.sys.ini

### PR DESCRIPTION
**Pull request by louis037**
French language created

### CODE REVIEW

**Comment by trob** [comment]
Hi, it would be a lot easier if you don't create a single patch/pull request for every single file.

**Comment by louis037** [comment]
Hello,

You’re right… 

I’ll do it next time

 

De : troester <notifications@github.com> 
Envoyé : lundi 4 mars 2019 15:59
À : Fabrik/fabrik <fabrik@noreply.github.com>
Cc : louis037 <ljorrot@free.fr>; Author <author@noreply.github.com>
Objet : Re: [Fabrik/fabrik] Create fr-FR.plg_fabrik_element_timestamp.sys.ini (#2164)

 

Hi, it would be a lot easier if you don't create a single patch/pull request for every single file.

**Comment by trob** [comment]
hmm,
https://github.com/Fabrik/fabrik/pull/2171
is conflicting
(maybe because of already merged pull requests?)
Can you split FR and GB pull requests?
I'd like to leave merging GB stuff to @cheesegrits because this is really core files.

But great work...

**Comment by louis037** [comment]
Well… I am a bit lost…

 

I don’see how to split it, especially for files already sent.

 

Another thing : I just modified the translations of the modules. Do you see them?

 

Thanks  for your encouragments

 

De : troester <notifications@github.com> 
Envoyé : lundi 4 mars 2019 18:11
À : Fabrik/fabrik <fabrik@noreply.github.com>
Cc : louis037 <ljorrot@free.fr>; Author <author@noreply.github.com>
Objet : Re: [Fabrik/fabrik] Create fr-FR.plg_fabrik_element_timestamp.sys.ini (#2164)

 

hmm,
#2171 <https://github.com/Fabrik/fabrik/pull/2171> 
is conflicting
(maybe because of already merged pull requests?)
Can you split FR and GB pull requests?
I'd like to leave merging GB stuff to @cheesegrits <https://github.com/cheesegrits>  because this is really core files.

But great work...

**Pull request merged**
