### PR TITLE
[minor] Improve List Data Prefilter layout

### PR DESCRIPTION
**Pull request by Sophist-UK**
1. Dropdown widths match select items.
2. Group Yes/No now BS button group.
3. Delete icon properly centred.

### CODE REVIEW

**Comment by Sophist-UK** [comment]
list_data_prefilter_improvements

**Comment by cheesegrits** [comment]
Have you tried this on a 15" laptop?

The reason I've left some of those filter settings narrower and not used a button group for Grouped is that when working on a laptop, those filter settings are already close to full screen width, and it's kind of  pain in the ass working with them when they exceed page width.

If you don't already use it, install Window Resizer ...

https://chrome.google.com/webstore/detail/window-resizer/kkelicaakdanhinjdeammmilcgefonfh?utm_source=chrome-app-launcher-info-dialog

... and see how your changes look in different windows sizes.  If you think they are usable at standard "small desktop" (1280x1024) I'll merge.

Maybe provide a screenshot at that screen size.

**Comment by Sophist-UK** [comment]
I did test this at the time I was coding it. If you have a browser window narrower than c. 1350px, then you get horizontal scrolling, but its all visible.

As far as I can recall this was true prior to this change too.

**Comment by Sophist-UK** [comment]
Now fits inside 1280px browser.

**Comment by Sophist-UK** [comment]
Still one bit of HTML to sort - whitespace to left of button group. Please wait until I have done that before you merge.

**Comment by Sophist-UK** [comment]
Ok - good to go.

**Pull request merged**
