### PR TITLE
hide checkbox per param

### PR DESCRIPTION
**Pull request by bauer-git**
Tried using fabrikHide class here instead but that (weirdly) caused the action buttons to be hidden too.

### CODE REVIEW

**Comment by pollen8** [comment]
hi - is there another part of the code which was not committed in this PR? It's not really clear what it is you are trying to achieve.

**Comment by bauer-git** [comment]
The checkboxes that are shown in a list are oftentimes really not needed (at least they don't really need to be shown, as they only take up horizontal space and their purpose can be confusing to the user). I just want to be able to easily hide them without having to write special CSS or javascript code for every list where they are unnecessary .

**Comment by bauer-git** [comment]
I just realized I never really answered your question (I seem to do that a lot).

And yes, sorry - it appears I didn't include the xml and language file additions for the new 'hidecheckbox' (Yes/No) parameter in the list configuration. Just thought t would be a simple request and easy to add.

**Comment by pollen8** [comment]
ah ok - generally its a lot easier to test if you update the PR so that all the code for one feature is in the same PR. Dont bother for this one though I'll merge in the 4 prs

**Pull request merged**
