### PR TITLE
Fix list sort icons

### PR DESCRIPTION
**Pull request by Sophist-UK**
1. Fix issue with calc fields which are also links showing with the <a> tags as text rather than tags.

2. Tweak sort icons so that they match Fabrik standards i.e. carets, and pointing in the current sort direction.

3. Various minor style improvements to list.js.

### CODE REVIEW

**Comment by cheesegrits** [comment]
Can no longer be merged automatically.

The reasonn I never merged this is the "minor stye improvements to list.js" are somewhat more than just "style", and I never had the time to fully review them all.

If you can resubmit against a current github so it can be autoatically merged, and preferably as separate PR's (at least split out the list.js into a separate PR), I'll merge.

**Comment by Sophist-UK** [comment]
:-1: 

When I submitted it, it merged correctly. That's what happens when YOU don't process PRs promptly.

**Comment by cheesegrits** [comment]
As I said I didn't merge it because it had extensive changes to list.js which had nothing to do with the subject of the PR, and unexplained changes to encoder.js.  We discussed this at some length in Skype back then.  PR's need to be focused on a single issue, with the minimal amount of code change in each one, so we don't wind up not merging because we aren't 100% sure about "the other stuff".

I'm just going through and clearing out the old, non mergable PR's.

**Comment by Sophist-UK** [comment]
When I get the time I will rework this and resubmit it (as separate PRs).

**Comment by cheesegrits** [comment]
Thanks.

**Pull request closed without merging**
