### PR TITLE
[FIX] Fullcalendar allday events

### PR DESCRIPTION
**Pull request by skurvish**
If either or both of the date elements have the "Show Time Selector" disabled we will treat the event as an all day event.

### CODE REVIEW

**Comment by skurvish** [comment]
I am rethinking this PR. I am not sure it is valid to force any event that is not showing the time selector to be an all day event. I envision people who might not show this selector but set the time in element javascript or onBeforeSave or similar plugins.

Might it make more sense to add an element selector on the database for the vis. If an element is chosen and that elements value is true, then treat as an all day event, otherwise use the time values. 

i think this would be more flexible. Thoughts?

**Comment by cheesegrits** [comment]
Yeah, I wasn't entirely sure this was the right approach when you submitted the PR.

Definitely a specific "All day event" option in the viz settings would be a better approach.

**Comment by skurvish** [comment]
OK, how do we purge this PR.

**Comment by cheesegrits** [comment]
Like that.

**Pull request closed without merging**
